services:
  - type: web
    name: policyforge
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
